require 'rbconfig'
require 'open-uri'
#require 'open_uri_redirections'
require 'fileutils'
include FileUtils::Verbose
require 'rake/clean'

URL = "https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2"
URL_bcf = "https://github.com/samtools/bcftools/releases/download/1.3.1/bcftools-1.3.1.tar.bz2"
task :download do
  open(URL) do |uri|
    File.open("samtools-1.3.1.tar.bz2",'wb') do |fout|
      fout.write(uri.read)
    end #fout
  end #uri

  open(URL_bcf) do |uri|
    File.open("bcftools-1.3.1.tar.bz2",'wb') do |fout|
      fout.write(uri.read)
    end #fout
  end #uri

end

task :compile do
  sh "tar xvfj samtools-1.3.1.tar.bz2"
  cd("samtools-1.3.1") do
    sh "make"
    cp('samtools', "/Users/ramirezr/Documents/public_code/helios/bioruby-samtools/ext/../lib/bio/db/sam/external")
  end #cd

  sh "tar xvfj bcftools-1.3.1.tar.bz2"
  cd("bcftools-1.3.1") do
    sh "make"
    cp('bcftools', "/Users/ramirezr/Documents/public_code/helios/bioruby-samtools/ext/../lib/bio/db/sam/external")
  end #cd
end

task :clean do
  cd("samtools-1.3.1") do
    sh "make clean"
  end
  rm("samtools-1.3.1.tar.bz2")
  rm_rf("samtools-1.3.1")
  rm("bcftools-1.3.1.tar.bz2")
  rm_rf("bcftools-1.3.1")
end

task :default => [:download, :compile, :clean]

