require 'rbconfig'
require 'open-uri'
require 'fileutils'
include FileUtils::Verbose
require 'rake/clean'

URL = "http://sourceforge.net/projects/samtools/files/samtools/1.2/samtools-1.2.tar.bz2/download"
URL2 = "https://github.com/samtools/bcftools/releases/download/1.2/bcftools-1.2.tar.bz2"

task :download do
  open(URL) do |uri|
    File.open("samtools-1.2.tar.bz2",'wb') do |fout|
      fout.write(uri.read)
    end #fout 
  end #uri

    open(URL2) do |uri|
    File.open("bcftools-1.2.tar.bz2",'wb') do |fout|
      fout.write(uri.read)
    end #fout 
  end #uri
end
    
task :compile do
  sh "tar xvfj samtools-1.2.tar.bz2"
  sh "tar xvfj bcftools-1.2.tar.bz2"
  cd("samtools-1.2") do
    sh "make"
    cp("samtools", "/Users/ramirezr/Documents/public_code/bioruby-samtools/ext/../lib/bio/db/sam/external")
  end #cd
  cd("bcftools-1.2") do
    sh "make"
    cp('bcftools', "/Users/ramirezr/Documents/public_code/bioruby-samtools/ext/../lib/bio/db/sam/external")
  end
end
  
task :clean do
  cd("samtools-1.2") do
    sh "make clean"
  end
  cd("bcftools-1.2") do
    sh "make clean"
  end
  rm("samtools-1.2.tar.bz2")
  rm_rf("samtools-1.2")
  rm("bcftools-1.2.tar.bz2")
  rm_rf("bcftools-1.2")
end

task :default => [:download, :compile, :clean]
  
